apiVersion: apps/v1
kind: Deployment
metadata:
  name: netapi-deployment
spec:
  selector:
    matchLabels:
      app: netapi
  template:
    metadata:
      labels:
        app: netapi
    spec:
      containers:
      - name: netapi
        image: netapi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: MongoDbSettings__Host
          value: mongodb-service
        - name: MongoDbSettings__Password
          valueFrom:
            secretKeyRef:
                name: netapi-secrets
                key: mongodb-password
        livenessProbe:
            httpGet:
                path: /health/live
                port: 80
        readinessProbe:
            httpGet:
                path: /health/ready
                port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: netapi-service
spec:
  type: LoadBalancer
  selector:
    app: netapi
  ports:
  - port: 80
    targetPort: 80

